version: '3'
services:
  dapp:
    build: .
    container_name: rbank-dapp
    ports:
      - "80:80"
      - "443:443"
    environment:
      - RBANK_CONTROLLER=0xCfEB869F69431e42cdB54A4F4f105C19C080A601
